### ISSUE TITLE
listening on UNIX sockets is insecure and exposes Xandikos to the world

### ISSUE THREAD

**Issue by schnusch** [jelmer/xandikos#134]
If Xandikos is instructed to listen on a UNIX socket it by default also listens on **0.0.0.0:8080**.

For `aiohttp.web.run_app` to only listen on a UNIX socket its host **and** port parameter must be `None` (see <https://github.com/aio-libs/aiohttp/blob/742a8b6/aiohttp/web.py#L353>) otherwise it will listen on IP.

Xandikos sets `listen_address` to `None` before calling aiohttp but `options.port` is always an integer and this will cause aiohttp to also create a `TCPSite` which calls [asyncio.loop.create_server](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server) with `host=None` which in turn creates a **listening socket on all interfaces**.

I don't see how it is possible to not listen on all interfaces when using UNIX sockets without patching Xandikos. #133 should fix this.

A simple test to see that aiohttp tries to listen on IP also is to run `xandikos -d . -l /tmp/xandikos.sock -p -1`. Setting the port to -1 will cause aiohttp to try to bind to 0.0.0.0:-1 and the bind call to fail.

**Comment by jelmer** [comment]
Thanks, completely missed that. I've merged your pull request and will put out a new release.

**Comment by morciej** [comment]
I don't understand. 8080/8081 are "always" used even if I run Xandikos with -p 8008 specifically to change it. Both Xandikos and Syncthing refuse to start if the other one is running. We need to be able to change this port from the command line.

Is this fixed in ver. 0.2.10?

(I think I have no choice but to keep transferring the calendar manually, because too many things are broken at either end. It's as usual a frustrating comedy of "this doesn't work, let's try another way - no that's borked too")

**Comment by morciej** [comment]
Too late. I got Radicale to work instead. I am not much for experimenting on a production server if I can avoid it, so I am not going to rip it out just to see if I can get Xandikos to work too. If you mean IPv6 port, I don't bother with enabling it on my desktop because my ISP doesn't.

**Comment by jelmer** [comment]
There's a --port and a --metrics-port argument
