### ISSUE TITLE
allow setting resource type

### ISSUE THREAD

**Issue by jelmer** [jelmer/xandikos#16]
e.g. MKCOL tries to set the resource type; it should be able to use this to change a plain collection into a calendar or address book.

**Comment by untitaker** [comment]
If I understand the code correctly, this issue prevents the user from using the `address-data`/`calendar-data` props on a REPORT because those properties are not supported on a simple `{DAV:}collection`. The core issue is that collections created with MKCOL with the resource types `calendar` and `collection` are stored as `collection` only, not as `calendar`.

**Comment by jelmer** [comment]
That's correct.
