### ISSUE TITLE
Run tests with CalDAVTester

### ISSUE THREAD

**Issue by hobarrera** [jelmer/xandikos#29]
This isn't really an issue, but more of a long term goal: I think it'd a good idea to eventually use [CalDAVTester](https://www.calendarserver.org/CalDAVTester.html) to test protocol handling and keep a good eye on standards compliance.

I know a few vendors (including Apple) use this right now to test interoperability, so eventually passing all tests with it would be a huge win.

**Comment by jelmer** [comment]
This would indeed be very nice.

There is some initial work to get this to run in compat/, though that's might not the best way to do it.

Caldavtester is less convenient to use than the vdirsyncer tests because it requires you to create a particular complex set of collections to run against. It won't create the collections in needs by itself.

**Comment by jelmer** [comment]
There is now a 'make check-caldavsyncer' target that runs testcaldav against xandikos.

I haven't been able to make this work in travis, since caldavtester requires Python2, and I haven't been able to get travis to run Python2 caldavtester against Python3 Xandikos. Help welcome.
