### ISSUE TITLE
Document how to create calendar

### ISSUE THREAD

**Issue by bugeaud** [jelmer/xandikos#74]
Creation of calendar might be obvious ... but it is not explained.

Docker create by default a tree in /data/dav/user1 :
  ./calendars/calendar
  ./contacts/addressbook
  ./inbox

But example of URL given is : 
http://dav.example.com/user/calendars/my_calendar

It will result in obvious Path not found according to default.

IMHO, there should be example matching the defaults and clear indication of what to add and the result URL to use to target it thru CalDAV.

**Comment by jelmer** [comment]
I've tried to clarify the README file to make this clear. Is this clearer?

**Comment by jelmer** [comment]
Ah, I didn't realize you were using the docker image.

XANDIKOSPATH is just where the data is stored locally, so that's an implementation detail that shouldn't matter.

The docker file sets the default to ``current_user_principal``  to /dav/user1 (https://github.com/jelmer/xandikos/blob/2a02d4af39122722496431f0623aad6f77748c1a/Dockerfile#L11), mostly as an example. 

Ideally we'd require that the user pass something in for the ``current_user_principal`` variable, so it's obvious to them where the calendar will be available.

I've added some more comments to the Dockerfile and a pointer in the README. Please do suggest improvements if you can think of any.

**Comment by jelmer** [comment]
I've also pushed some changes so that the root web page now lists the principal paths.
