### ISSUE TITLE
homeserver/dav/joe  homeserver/dav/jane

### ISSUE THREAD

**Issue by stappersg** [jelmer/xandikos#76]
Hello,

What I want to achieve is that both Joe and Jane can use their own silo on the same homeserver.
No need for sharing agendas.

Joe configures   http://homeserver/dav/joe 
Jane configures  http://homeserver/dav/jane

Homeserver does serve more then CardDAV/CalDAV

The idea is that homeserver has webserver configured so that requests for /dav/joe needs joe password to get to his xandikos git repo.  Requests for dav/jane need her password to reach her xandikos git repo.

I'm aware that #61 , #52 and #6 are currently open issues.

Thing I want to know: Would it be possible with current Xandikos and (alot) webserver config tweaking?

Can it be done with 1 Xandikos instance?
Or would there be one for each user   ( Each xandikos server running on a separate port )  ?

Any advice for
```
env = XANDIKOSPATH=...
env = CURRENT_USER_PRINCIPAL=...
```
??

**Comment by jelmer** [comment]
The only way to do this at the moment is to run two different Xandikos server instances. You could run them on separate ports and then add a reverse proxy that forwards to these ports as appropriate (/dav/joe => localhost:8081/dav/joe, /dav/jane => localhost:8082/dav/jane)

You would need to run one server with uwsgi config like this:

    socket = localhost:8081
    env = XANDIKOSPATH=/var/lib/xandikos/joe
    env = CURRENT_USER_PRINCIPAL=/dav/joe

and one like:

    socket = localhost:8082
    env = XANDIKOSPATH=/var/lib/xandikos/jane
    env = CURRENT_USER_PRINCIPAL=/dav/jane

(As you mention, once #61 and #52 are implemented, you would be able to just use a single Xandikos server rather than two)
